general:
  oregin_enabled: true 					# Whether OreGin machines are enabled
  smelter_enabled: false 				# Whether Smelter machines are enabled (LEAVE AS FALSE)
  cloaker_enabled: true 				# Whether Cloaker machines are enabled
  citadel_enabled: true 				# Whether server has Citadel enabled
  save_cycle: 10 						# Time in minutes between periodic saves of machines
  
cloaker_general:
  update_cycle: 20 						# How often Cloakers are updated (IN TICKS)
  max_tiers: 3 							# The max tiers for Cloakers to upgrade through
  cloaker_activated: JACK_O_LANTERN 	# The material used for Cloaker machines while activated
  cloaker_deactivated: PUMPKIN 			# The material used for Cloaker machines while deactivated
  cloaker_upgrade_wand: YELLOW_FLOWER 	# The item used to upgrade Cloakers
  cloaker_activation_wand: RED_ROSE 	# The item used to activate/deactivate cloakers
  
  cloaker_tier_properties:
    tier1:								# Tier 1 Cloaker Properties
      upgrade_type: IRON_BLOCK			# The material used to upgrade to this tier
      upgrade_amount: 16				# The amount of upgrade_type items used to upgrade
      fuel_time_duration: 900			# How long a cloak will last before having to refuel (IN SECONDS)
      fuel_type: REDSTONE				# The material used to fuel cloaking
      fuel_amount: 16					# The amount of fuel_type items used to fuel
      cloak_width: 3					# The width of the cloaking field (IN BLOCKS)
      cloak_height: 3					# The height of the cloaking field (IN BLOCKS)
      cloak_depth: 3					# The depth of the cloaking field (IN BLOCKS)
      visibility_range: 5				# How close a player must be to see the cloaked blocks (IN BLOCKS)
    tier2:								# Tier 2 Cloaker Properties
      upgrade_type: IRON_BLOCK
      upgrade_amount: 92
      fuel_time_duration: 1200
      fuel_type: COAL
      fuel_amount: 8
      cloak_width: 9
      cloak_height: 9
      cloak_depth: 9
      visibility_range: 13
    tier3:								# Tier 3 Cloaker Properties
      upgrade_type: GOLD_BLOCK
      upgrade_amount: 42
      fuel_time_duration: 1800
      fuel_type: IRON_INGOT
      fuel_amount: 12
      cloak_width: 21
      cloak_height: 21
      cloak_depth: 21
      visibility_range: 25
  
oregin_general:
  update_cycle: 5						# How often OreGins should be updated (IN TICKS)
  maximum_block_breaks_per_cycle: 500	# The maximum number of total block breaks per cycle
  max_tiers: 7							# The maximum number of tiers for OreGins
  oregin_upgrade_wand: YELLOW_FLOWER	# The item used to upgrade and create OreGins
  oregin_activation_wand: RED_ROSE		# The item used to activate/deactivate OreGins
  oregin_repair_wand: IRON_SPADE		# The item used to repair OreGins
  oregin_light_on: REDSTONE_LAMP_ON		# The material used when the OreGin is activated
  oregin_light_off: REDSTONE_LAMP_OFF	# The material used when the OreGin is deactivated
  redstone_activation_enabled: true		# Whether OreGins can be activated using redstone
  repairing_enabled: true				# Whether OreGins can be broken and repaired
  lava_mining_enabled: true				# Whether OreGins can mine lava blocks
  water_mining_enabled: true			# Whether OreGins can mine water blocks
  junk_destruction_enabled: true		# Whether OreGins will destroy item drops from 'JUNK' blocks
  valuables:							# List of 'valuable' blocks
  - IRON_ORE
  - GOLD_ORE
  - DIAMOND_ORE
  - LAPIS_ORE
  junk:									# List of 'junk' blocks
  - STONE
  - DIRT
  - GRAVEL
  - SAND
  - GRASS
  indestructible:						# List of 'indestructible' blocks
  - BEDROCK
  - OBSIDIAN
  oregin_tier_properties:
    tier1:								# Tier 1 OreGin Properties
      max_mining_distance: 20			# The maximum distance this OreGin tier can mine
      max_block_breaks: 160				# Number of blocks mined before OreGin breaks
      mining_delay: 40					# The delay between mining operations
      retrieve_valuables: false			# Whether valuable drops will be teleported to the OreGin
      fuel_type: REDSTONE				# The material used for fueling this tier
      fuel_amount: 1					# The amount of fuel_type items used to fuel one mining opreation
      upgrade_material: IRON_BLOCK		# The type of material used to upgrade to this tier
      upgrade_amount: 5					# The amount of upgrade_material used to upgrade
      repair_material: IRON_BLOCK		# The type of material used to repair this tier
      repair_amount: 2					# The amount of repair_material items used to repair
      shaft_width: 1					# The width of the shaft mined
      shaft_height: 1					# The height of the shaft mined
    tier2:								# Tier 2 OreGin Properties
      max_mining_distance: 35
      max_block_breaks: 300
      mining_delay: 30
      retrieve_valuables: false
      fuel_type: REDSTONE
      fuel_amount: 2
      upgrade_material: IRON_BLOCK
      upgrade_amount: 20
      repair_material: IRON_BLOCK
      repair_amount: 8
      shaft_width: 3
      shaft_height: 1   
    tier3:								# Tier 3 OreGin Properties
      max_mining_distance: 50
      max_block_breaks: 1000
      mining_delay: 20
      retrieve_valuables: false
      fuel_type: COAL
      fuel_amount: 3
      upgrade_material: IRON_BLOCK
      upgrade_amount: 48
      repair_material: IRON_BLOCK
      repair_amount: 20
      shaft_width: 3
      shaft_height: 3 
    tier4:								# Tier 4 OreGin Properties
      max_mining_distance: 75
      max_block_breaks: 1875
      mining_delay: 15
      retrieve_valuables: false
      fuel_type: COAL
      fuel_amount: 9
      upgrade_material: GOLD_BLOCK
      upgrade_amount: 64
      repair_material: GOLD_BLOCK
      repair_amount: 28
      shaft_width: 5
      shaft_height: 5
    tier5:								# Tier 5 OreGin Properties
      max_mining_distance: 100
      max_block_breaks: 3000
      mining_delay: 10
      retrieve_valuables: true
      fuel_type: IRON_INGOT
      fuel_amount: 5
      upgrade_material: DIAMOND_BLOCK
      upgrade_amount: 32
      repair_material: DIAMOND_BLOCK
      repair_amount: 14
      shaft_width: 6
      shaft_height: 6
    tier6:								# Tier 6 OreGin Properties
      max_mining_distance: 125
      max_block_breaks: 5000
      mining_delay: 5
      retrieve_valuables: true
      fuel_type: GOLD_INGOT
      fuel_amount: 5
      upgrade_material: DIAMOND_BLOCK
      upgrade_amount: 64
      repair_material: DIAMOND_BLOCK
      repair_amount: 30
      shaft_width: 8
      shaft_height: 8
    tier7:								# Tier 7 OreGin Properties
      max_mining_distance: 150
      max_block_breaks: 10000
      mining_delay: 5
      retrieve_valuables: true
      fuel_type: DIAMOND
      fuel_amount: 3
      upgrade_material: DIAMOND_BLOCK
      upgrade_amount: 128
      repair_material: DIAMOND_BLOCK
      repair_amount: 60
      shaft_width: 11
      shaft_height: 11